### ISSUE TITLE
HTTPConnectionPool(host='localhost', port=5002): Max retries exceeded with url: /signup

### ISSUE THREAD

**Issue by B0bbyB0livia** [casperbh96/Flask-Stripe-MySQL-Bootstrapped#3]
Hi,
I started playing with this concep of microservices. I am intrigued and would like to dig in deeper in this sample..

On signup i get an error (as below). I suspect it has to do with additional service being requested on other ports ...not open by flask.
Perhaps i'm wrong...any help would be appreciated

127.0.0.1 - - [29/Sep/2020 22:42:08] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [29/Sep/2020 22:42:24] "POST /signup HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7feb243d40f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5002): Max retries exceeded with url: /signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb243d40f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mlub777/Documents/Flask-Sites/trademe/app/FrontendMicroservice/service_calls/call_user_service.py", line 14, in signup
    r = requests.post('http://' + current_app.config['BASE_URL'] + ':' +  current_app.config['USER_PORT'] + '/signup', json=data)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5002): Max retries exceeded with url: /signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb243d40f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by casperbh96** [comment]
How did you start the microservices?

**Comment by B0bbyB0livia** [comment]
running local on debian with 
export FLASK_APP=main_frontend.py
flask run --debugger

**Comment by B0bbyB0livia** [comment]
I found the issue...I understand the architecture a little better now. 
1. because I am NOT using docker, i had to start all 4 services simultaneously and manually on their respective ports.
2. docker would have done this in the background, however, when i tested the vanilla install method with docker, i ran into mysql connection issues.
3. this is not the case when running them seprately.

Thanks for your quick response. I can see alot of benefit with microservices, stacked in this way.

Good job!

**Comment by argoapps** [comment]
@B0bbyB0livia I have this running on Google Cloud on a public URL and have run into the same problem.  My database connections work fine and all my databases and tables have been created on startup.  

How did you solve the issue you had as I have the exact same problem?  I was unsure what to put as my BASE_URL in the config.py.  As localhost didn't work I tried 0.0.0.0 and the public URL provided by Google but none work.

**Comment by argoapps** [comment]
I have each up and running in Cloud Run but I am still running into the error.

<img width="1021" alt="Screenshot 2021-09-22 at 13 35 31" src="https://user-images.githubusercontent.com/80706503/134347421-b8b15810-d61b-41f8-bb31-9381dba68ecf.png">

**Comment by argoapps** [comment]
I'm having trouble getting them to communicate between each other, even though they are assigned to the correct ports.
